name: Run Reddit Highlights Bot

on:
  schedule:
    - cron: '*/5 23 * * *'  # 7PM–8PM EST
    - cron: '*/5 0 * * *'   # 8PM–9PM EST
    - cron: '*/5 1 * * *'   # 9PM–10PM EST
    - cron: '*/5 2 * * *'   # 10PM–11PM EST
    - cron: '*/5 3 * * *'   # 11PM–12AM EST
    - cron: '*/5 4 * * *'   # 12AM–1AM EST
  workflow_dispatch:  # allow manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Microsoft Core Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer fontconfig

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        env:
            REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
            REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
            REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}

            TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
            TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
            TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
            TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
            TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
            TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}

            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_ANON_PUBLIC_API_KEY: ${{ secrets.SUPABASE_ANON_PUBLIC_API_KEY }}
            DB_PWD: ${{ secrets.DB_PWD }}

        run: python main.py
